const canvasWidth = 800,
      canvasHeight = 450,
      noteWidth = 24,
      noteHeight = 16,
      noteRadius = 2,
      noteOffset = 0.15,
      keyCount = 8,
      trackWidth = noteWidth * keyCount,
      speed = 5;